apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-payment-authorizer-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.3"
  POD_NAME: "go-payment-authorizer..eks-arch-01-02"
  PORT: ":65000"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  SETPOD_AZ: "false"
  ENV: "dev"  

  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector-collector.default.svc.cluster.local:4317"
  USE_STDOUT_TRACER_EXPORTER: "false"
  USE_OTLP_COLLECTOR: "true" 
  AWS_CLOUDWATCH_LOG_GROUP_NAMES: "/dock/eks/eks-arch-01-02"

  NAME_SERVICE_00: "go-tokenization-grpc"
  URL_SERVICE_00: "dns:///nlb-go-tokenization-grpc-ead977511b03d593.elb.us-east-2.amazonaws.com:65001"

  NAME_SERVICE_01: "go-limit"
  URL_SERVICE_01: "https://nlb-eks-arch-02.architecturedev.caradhras.io"
  METHOD_SERVICE_01: "POST"
  HOST_SERVICE_01: "go-limit.architecturedev.caradhras.io"
  CLIENT_HTTP_TIMEOUT_01: "5"

  NAME_SERVICE_02: "go-ledger"
  URL_SERVICE_02: "https://nlb-eks-arch-01-02.architecture.caradhras.io"
  METHOD_SERVICE_02: "POST"
  HOST_SERVICE_02: "go-ledger.architecture.caradhras.io"
  CLIENT_HTTP_TIMEOUT_02: "5"

  NAME_SERVICE_03: "go-card"
  URL_SERVICE_03: "https://nlb-eks-arch-02.architecturedev.caradhras.io" 
  METHOD_SERVICE_03: "POST"
  HOST_SERVICE_03: "go-card.architecturedev.caradhras.io"
  CLIENT_HTTP_TIMEOUT_03: "5"

  NAME_SERVICE_04: "go-account"
  URL_SERVICE_04: "https://nlb-eks-arch-01-02.architecture.caradhras.io" 
  METHOD_SERVICE_04: "GET"
  HOST_SERVICE_04: "go-account.architecture.caradhras.io"
  CLIENT_HTTP_TIMEOUT_04: "5"